language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - "composer self-update"
  - "composer --version"
  - "composer install --no-interaction"

script:
  - "./vendor/bin/phpunit -c phpunit.xml.dist"
